### ISSUE TITLE
Uptime History

### ISSUE THREAD

**Issue by AdrianoCahete** [HeadTalker/uptime-robot#2]
UptimeRobot shows online/offline latest events from each monitor (up/down/start/pause status, time, reason, duration) and latest downtime. Can uptime-robot have this?

**Comment by HeadTalker** [comment]
Hi,

Thanks for opening an issue.

I think what your asking for is something like "Latest Events For All Monitors (up, down, start, pause)" on uptimerobot.com dashboard with the table of events?

I don't see how to do this via the API https://uptimerobot.com/api .  If you see a way let me know.  I may be missing over an endpoint or something.

If theres not an endpoint what could be done is this could hook up with a database to save the data.  Then the events could be queried from the database and not rely on the API.  I've been thinking about this for a while.  Because currently we only get a small period of logs and storing the data would be more helpful in the long run I think.

Also how are you using this or planning to use this?  I am not sure whether to keep this like a status page 1 pager or roll out a dashboard.

**Comment by AdrianoCahete** [comment]
> I think what your asking for is something like "Latest Events For All Monitors (up, down, start, pause)" on uptimerobot.com dashboard with the table of events?

Exactly.

What i want to do is make something like [StatusPage.io](http://metastatuspage.com/), but not like real incidents, but latest events itself.

But in fact i din't search API, just see the website itself. Searching now in API docs, i find the ```logs```` in ```getMonitors```` endpoint. I think that are the events.

**Comment by HeadTalker** [comment]
I see.  I will dig deeper into it later this week.  I see this on the API docs - "responseTimesStartDate - optional and works only for the Pro Plan as 24 hour+ logs are kept only in the Pro Plan" .  I will need to test but I am thinking that this isn't possible via the API.   A database + cronjob may be a good work around if its not possible via the API.

**Comment by AdrianoCahete** [comment]
Testing fastly here, i find if you pass the ```log=1``` parameter, api returns all history, including date and log type, that can be:

- 1 - down
- 2 - up
- 99 - paused
- 98 - started

Test request: ``` https://api.uptimerobot.com/getMonitors?apiKey=APIKEY&logs=1 ```

**Comment by HeadTalker** [comment]
Oh awesome!  Thanks for finding that.  I just checked it out.  That will work.

**Comment by HeadTalker** [comment]
https://github.com/HeadTalker/uptime-robot/commit/93dcc131c47ed0dbb3f1019bf187c3c9ec947cb1

It has been added
